# Generated by Django 4.2.7 on 2023-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=300)),
                ('Phone_number', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30)),
                ('RegTime', models.DateTimeField()),
            ],
        ),
    ]
