# Generated by Django 4.2.7 on 2023-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RegTime',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
